#!/usr/bin/env bash
# A bash script that installs, configures and starts the server
apt-get -y update
apt-get -y install nginx
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
rewrite="server {
        listen 80;
        listen [::]:80;

        root /var/www/html;
        index index.html index.htm index.nginx-debian.html;

        server_name _;
	location /redirect_me {
            return 301 https://www.github.com;
}"

echo -e "$rewrite" > /etc/nginx/sites-available/redirect
ln -sf /etc/nginx/sites-available/redirect /etc/nginx/sites-enabled/redirect
sudo nginx -t
service nginx restart
