#!/usr/bin/env bash

# install nginx web server that listens on port 80

# Install Nginx
sudo apt-get update
sudo apt-get -y install nginx

# Start the nginx service
sudo service nginx start

# Create the index.html file with the "Hello World!" message
sudo echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null

# add a 404 page
sudo echo "Ceci n'est pas une page" > /var/www/html/404.html
string_for_replacement="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$string_for_replacement/" /etc/nginx/sites-available/default

# redirect the page 301 permanent
string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.github.com permanent;"
sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# Configure Nginx to add custom HTTP header
sudo sed -i "s/include \/etc\/nginx\/sites-enabled\/\*;/&\n\tadd_header X-Served-By \"$HOSTNAME\";/" /etc/nginx/nginx.conf

# Restart Nginx
sudo service nginx restart
