#!/usr/bin/env bash
# a Bash script that configures a server by making a short and sweet fix
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx start
pkill nginx
